---
# tasks file for apigee-opdk-server-self
- name: Validate that server_types was provided
  fail:
    msg: "Please provide the server_types"
  when: server_types is not defined

- name: Obtain server self report for {{ server_type }}
  ignore_errors: yes
  opdk_server_self:
    server_type: '{{ item }}'
    username: '{{ opdk_user_email }}'
    password: '{{ opdk_user_pass }}'
  with_items: '{{ server_types }}'

- name: Construct self report variable name
  set_fact:
    self_report_name: 'edge_{{ server_type }}_self'

- name: Server self attributes report
  debug:
    msg: "{{ hostvars[inventory_hostname][self_report_name] }}"